name: healthpulse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.16.0
  google_sign_in: ^6.2.1
  http: ^0.13.6
  speech_to_text: ^6.3.0
  cupertino_icons: ^1.0.2
  flutter_tts: ^3.7.0
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
