// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcZAgSsHyeMzwEyoVOfG7yLb5u9RtpoIA',
    appId: '1:583337509230:web:0d2ff6d90d3cf77b7a417f',
    messagingSenderId: '583337509230',
    projectId: 'healthpulse-b54f5',
    authDomain: 'healthpulse-b54f5.firebaseapp.com',
    storageBucket: 'healthpulse-b54f5.firebasestorage.app',
    measurementId: 'G-GFHJ63GHWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnzmI5H1lQWNvULCOa-MFFf0ogzyjS3MI',
    appId: '1:583337509230:android:24dd83138a89d8ee7a417f',
    messagingSenderId: '583337509230',
    projectId: 'healthpulse-b54f5',
    storageBucket: 'healthpulse-b54f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxsDxsc2v2SUsie4xmscnxP82VHhG5Oew',
    appId: '1:583337509230:ios:7e8fb88f26541b6d7a417f',
    messagingSenderId: '583337509230',
    projectId: 'healthpulse-b54f5',
    storageBucket: 'healthpulse-b54f5.firebasestorage.app',
    iosBundleId: 'com.example.healthpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxsDxsc2v2SUsie4xmscnxP82VHhG5Oew',
    appId: '1:583337509230:ios:7e8fb88f26541b6d7a417f',
    messagingSenderId: '583337509230',
    projectId: 'healthpulse-b54f5',
    storageBucket: 'healthpulse-b54f5.firebasestorage.app',
    iosBundleId: 'com.example.healthpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcZAgSsHyeMzwEyoVOfG7yLb5u9RtpoIA',
    appId: '1:583337509230:web:25bc018c1f51f5bf7a417f',
    messagingSenderId: '583337509230',
    projectId: 'healthpulse-b54f5',
    authDomain: 'healthpulse-b54f5.firebaseapp.com',
    storageBucket: 'healthpulse-b54f5.firebasestorage.app',
    measurementId: 'G-PYJF3MDNNX',
  );
}
